# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - MF-BZ-data

on:
  push:
    branches:
      - autotune
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'MF-BZ-data'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e4b2e93106f948ef9bf444f0e1601dd2 }}
        package: '${{ github.workspace }}/target/*.jar'